name: stacked_todo_demo
description: A demo app using stacked architecture

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  stacked: ^3.5.0
  stacked_services: ^1.2.0
  get_it: ^8.2.0
  injectable: ^2.3.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  hive_generator: ^2.0.1
  build_runner: ^2.4.9
  analyzer: ^6.11.0
  _fe_analyzer_shared: ^76.0.0

dependency_overrides:
  analyzer: ^6.11.0
  _fe_analyzer_shared: ^76.0.0
